services:
  laravel_app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - laravel_app
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  node:
      image: node:20
      container_name: laravel_node
      working_dir: /var/www
      volumes:
          - ./:/var/www
      networks:
          - laravel
      command: tail -f /dev/null

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
